@startuml
autonumber

 -> Jeu: deplacer(pos : String)
activate Jeu

Jeu -> Personnage: setX(x : int)
activate Personnage
Jeu <-- Personnage
deactivate Personnage

Jeu -> Personnage: setY(y : int)
activate Personnage
Jeu <-- Personnage
deactivate Personnage

<-- Jeu
deactivate Jeu
@enduml