@startuml

class Main {}

class Labyrinthe {
    - {static} taille : int
    + Labyrinthe()
    + ArrayList<Case> GetCasesLibres()
    + void genererMurs(int choix)
}
Labyrinthe "1" --> "*" Case : - cases

class Case {
    - x : int
    - y : int
    - libre : boolean
    + Case(int x, int y)
    + boolean : getLibre()
    + int : getX()
    + int : getY()
}

class Mur extends Case {
    + Color getCouleur();
}

class Sol extends Case {
    + Color getCouleur();
}

abstract class Entite {
    - x : Int
    - y : Int
    - pv : int
    + Entite(JeuPerso jeu)
    + attaquer(Entite e)
    + subirDegats()
}

class Personnage extends Entite {
    + Personnage()
    + String toString()
    + void seDeplacer(Commande c)
}

class Monstre extends Entite {
    + Monstre(int x, int y)
    + void seDeplacer(ArrayList<Case> libres)
}

interface Jeu {
    + void evoluer()
    + boolean etreFini()
}

interface DessinJeu {
    + void dessiner()
}

class JeuPerso implements Jeu {
    + JeuPerso()
    + String toString()
    + void evoluer(Commande commande)
    + boolean etreFini()
    + Personnage getPj()
    + void deplacerMonstres()
    + void genererMonstres(int nbMonstres)
    + ArrayList<Case> GetCasesLibres()
    + Labyrinthe getLabyrinthe()
}
JeuPerso "1" --> "1" Labyrinthe : - labyrinthe
JeuPerso "1" --> "1" Personnage : - pj
JeuPerso "1" --> "*" Monstre : - monstres

class DessinPerso implements DessinJeu {
    - {static} int tailleCase
    + DessinPerso(Jeu j)
    + void dessinerObjet(String s, int x, int y, BufferedImage im)
    + void dessiner(BufferedImage im)
}
DessinPerso "1" -> "1" JeuPerso : - jeu

@enduml